baseURL = "http://dachad.github.io/devops-training/"
languageCode = "es"
title = "Devops training BCN"

theme = "reveal-hugo"
publishDir = "docs/"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
custom_theme = "custom.css"
slide_number = true
